services:
  - type: web
    name: supabase-backup
    env: node
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y postgresql-client
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
